version: '2'
services:
    mysql:
        image: mysql:5.7
        env_file:
            - mysql.env
#          environment:
#              - MYSQL_ROOT_PASSWORD=test
#              - MYSQL_PORT_3306_TCP_PORT=3306
#              - MYSQL_DATABASE=cattleya
        ports:
            - "3306:3306"
#          exports:

#      cattleya:
#          build: app/
