version: '2'
services:
    mysql:
        build: ./mysql
        env_file:
            - ./mysql/mysql.env
#          ports:
        expose:
            - "3306"

    cattleya:
        build: ./app
        env_file:
            - ./app/app.env
            - ./mysql/mysql.env
        ports:
            - "8080:8080"
        links:
            - mysql

